use qemu exit code instead of text grep

diff --git a/.github/workflows/uring-kernel-version-test.yml b/.github/workflows/uring-kernel-version-test.yml
--- a/.github/workflows/uring-kernel-version-test.yml
+++ b/.github/workflows/uring-kernel-version-test.yml
@@ -72,6 +72,10 @@ jobs:
           ip link set lo up
 
           mkdir -p /dev
+
+          # This is required for setting an exit code in QEMU
+          mknod /dev/port c 1 4
+
           # create device nodes, as some tests require them
           mknod /dev/null c 1 3
           mknod /dev/zero c 1 5
@@ -82,8 +86,16 @@ jobs:
           mkdir -p /tmp && mount -t tmpfs -o mode=1777 tmpfs /tmp
           # for f in /bin/tests/*; do RUST_BACKTRACE=1 "$f" ; done
 
+
+          exit_code=0
+
           # Run the io_uring test binary
-          /bin/io-uring-test
+          RUST_BACKTRACE=1 /bin/io-uring-test || exit_code=1
+
+          [ $exit_code -eq 0 ] || printf '\x01' \
+            | dd of=/dev/port bs=1 seek=244 count=1 conv=notrunc 2>/dev/null
+
+          /sbin/poweroff -f
 
           EOF
           chmod +x initramfs/init
@@ -93,14 +105,16 @@ jobs:
       - name: Run tests in QEMU
         run: |
           qemu-system-x86_64 \
+            -device isa-debug-exit,iobase=0xf4,iosize=0x04 \
             -kernel linux-${{ env.KERNEL_VERSION }}/arch/x86/boot/bzImage \
             -initrd initramfs.cpio.gz \
             -netdev user,id=net0 \
             -device e1000,netdev=net0 \
             -append "console=ttyS0 rootfstype=ramfs panic=1" \
-            -nographic -no-reboot -m 1024 -action panic=exit-failure 2>&1 | tee qemu-output.log
+            -nographic -no-reboot -m 1024 -action panic=exit-failure
+
           # qemu always exits with 0, so we check if the tests passed by using grep.
-          if grep -q "test result: FAILED" qemu-output.log; then
+          if [ $? -ne 0 ]; then
             echo "tests failed (QEMU exited abnormally)"
             exit 1
           else
